### ISSUE TITLE
class org.osaf.caldav4j.example.CalDavCollectionManager does not compile

### ISSUE THREAD

**Issue by mislocin** [caldav4j/caldav4j#72]
I was looking for documentation / examples on how to use caldav4j when I discovered that CalDavCollectionManager class does not compile. A class which it extends (CalDAVCalendarCollection) does not exist in the project.

**Comment by TheAntimist** [comment]
@mislocin Sorry for the lack of documentation, that is one of the few things which were supposed to have been done. The examples haven't been updated to reflect the current state of the project.

But you can look at the [tests here](https://github.com/caldav4j/caldav4j/tree/master/src/test/java/org/osaf/caldav4j/methods) for now.

This issue is actually the same as #66, hence, I will be closing it. But if further help is required, feel free to add it here.

**Comment by ioggstream** [comment]
@mislocin could you please reference the broken docs?
